---
# HassMediaSearchAndPlay - default
# example: játszd le a következőt Pink Floyd
# slots: {search_query}

language: "hu"
data:
  - sentences:
      - "(játszd le|indítsd [el]) a következőt {search_query}"
    response: "default"
