---
# HassNevermind - default
# example: mindegy

language: "hu"
data:
  - sentences:
      - "mindegy"
      - "nem baj"
      - "hagyd"
      - "mégsem"
      - "semmi"
      - "felejtsd el"
    response: "default"
