---
# HassTimerStatus - default
# example: mennyi idő van hátra az időzítőből

language: "hu"

data:
  - sentences:
      - "[mi az ]időzítő állapot[a]"
      - "mennyi idő van hátra"
      - "mennyi van [még] hátra az időzítőből"
    response: "default"
